---
name: Main

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel setuptools
          pip install --requirement requirements.txt
      - name: Run tests
        run: |
          pytest
